name: Build-All

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    name: Build Linux Executables
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make-clean
      run: make clean
    - name: make-linux
      run: make all-linux
    - name: make-clean
      run: make clean
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch
        git add .
        git commit -m "Auto commit after compilation"
        git pull
        git merge
        git push origin master
  job2:
    name: Build Windows Executables
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install make and mingw
      run: |
        choco install make mingw
    - name: make-clean
      run: make clean
    - name: make-win
      run: make all-win
    - name: make-clean
      run: make clean
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch
        git add .
        git commit -m "Auto commit after compilation"
        git pull
        git merge
        git push origin master
  job3:
    name: Build MacOS Executables
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make-clean
      run: make clean
    - name: make-macos
      run: make all-macos
    - name: make-clean
      run: make clean
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch
        git add .
        git commit -m "Auto commit after compilation"
        git pull
        git merge
        git push origin master

